name: Daily Marketing News Collector

on:
  schedule:
    - cron: '0 2 * * *'  # 한국시간 11:00 (UTC 02:00)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  collect-and-send-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Collect and send marketing news
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        echo "Starting marketing news collection..."
        python news_collector.py
        echo "News collection completed!"
